name: Check ARM Templates

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      # with:
      #   since_last_remote_commit: true 

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Get list of changed files
      id: changed-files-2
      run: |
        git fetch origin master
        git diff --name-only @{u} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Checkov
      run: pip install checkov
      continue-on-error: true



    - name: Install ARM Template Toolkit
      run: |
        npm install -g @microsoft/arm-ttk

    - name: Run ARM Template Toolkit
      run: |
        arm-ttk/arm-ttk.ps1 -TemplatePath ./templates/function-app.json
