name: Check ARM Templates

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Checkov
      run: pip install checkov
      continue-on-error: true

    - name: Run Checkov
      run: checkov -d .

    - name: Install ARM Template Toolkit
      run: |
        npm install -g @microsoft/arm-ttk

    - name: Run ARM Template Toolkit
      run: |
        arm-ttk/arm-ttk.ps1 -TemplatePath ./templates/function-app.json
